import 'package:get/get_core/src/get_main.dart';
import 'package:get/get_instance/src/bindings_interface.dart';
import 'package:get/get_instance/src/extension_instance.dart';
import 'package:get/get_navigation/src/routes/get_route.dart';
import '../bind/aditional_binding.dart';
import '../bind/all_category_binding.dart';
import '../bind/category_binding.dart';
import '../bind/category_preview_binding.dart';
import '../bind/certificate_binding.dart';
import '../bind/change_password_binding.dart';
import '../bind/chat_binding.dart';
import '../bind/document_binding.dart';
import '../bind/faq_binding.dart';
import '../bind/favorite_binding.dart';
import '../bind/forgot_binding.dart';
import '../bind/home_binding.dart';
import '../bind/home_vendor_binding.dart';
import '../bind/inbox_binding.dart';
import '../bind/licence_binding.dart';
import '../bind/login_binding.dart';
import '../bind/navigation_binding.dart';
import '../bind/notification_binding.dart';
import '../bind/onboard_binding.dart';
import '../bind/otp_binding.dart';
import '../bind/otp_binding.dart';
import '../bind/privacy_binding.dart';
import '../bind/profile_binding.dart';
import '../bind/register_binding.dart';
import '../bind/request_binding.dart';
import '../bind/reset_binding.dart';
import '../bind/review_rating_binding.dart';
import '../bind/setting_binding.dart';
import '../bind/splash_binding.dart';
import '../bind/summary_binding.dart';
import '../bind/terms_binding.dart';
import '../bind/update_binding.dart';
import '../bind/vendor_phone_binding.dart';
import '../bind/vendor_profile_binding.dart';
import '../bind/verification_binding.dart';
import '../bind/verify_binding.dart';
import '../bind/welcome_binding.dart';
import '../views/aditional/screen/aditional_screen.dart';
import '../views/all_category/screen/all_category_screen.dart';
import '../views/auth/forgot/screen/forgot_screen.dart';
import '../views/auth/login/screen/login_screen.dart';
import '../views/auth/register/screen/register_screen.dart';
import '../views/auth/reset/screen/reset_screen.dart';
import '../views/auth/verification/screen/verification_screen.dart';
import '../views/auth/verify/screen/verify_screen.dart';
import '../views/category/screen/category_screen.dart';
import '../views/category_preview/screen/category_preview_screen.dart';
import '../views/certificate/screen/certificate_screen.dart';
import '../views/change_password/screen/change_password_screen.dart';
import '../views/chat/screen/chat_screen.dart';
import '../views/congratulations/controller/congratulations_controller.dart';
import '../views/congratulations/screen/congratulations_screen.dart';
import '../views/document/screen/document_screen.dart';
import '../views/faq/screen/faq_screen.dart';
import '../views/favorite/screen/favorite_screen.dart';
import '../views/home/screen/home_screen.dart';
import '../views/home_vendor/screen/home_vendor_screen.dart';
import '../views/inbox/screen/inbox_screen.dart';
import '../views/licence/screen/licence_screen.dart';
import '../views/navigation/screen/navigation_screen.dart';
import '../views/notification/screen/notification_screen.dart';
import '../views/onboard/screen/onboard_screen.dart';
import '../views/otp/screen/otp_screen.dart';
import '../views/privacy/screen/privacy_screen.dart';
import '../views/profile/screen/profile_screen.dart';
import '../views/request/screen/request_screen.dart';
import '../views/review_rating/screen/review_rating_screen.dart';
import '../views/setting/screen/setting_screen.dart';
import '../views/splash/screen/splash_screen.dart';
import '../views/summary/screen/summary_screen.dart';
import '../views/terms/screen/terms_screen.dart';
import '../views/update/screen/update_screen.dart';
import '../views/vendor_phone/screen/vendor_phone_screen.dart';
import '../views/vendor_profile/screen/vendor_profile_screen.dart';
import '../views/welcome/screen/welcome_screen.dart';

part 'pages.dart';

class Routes {
  static var list = RoutePageList.list;
static const otpScreen = '/otpScreen';
  static const aditionalScreen = '/aditionalScreen';
  static const vendor_verificationScreen = '/vendor_verificationScreen';
  static const vendor_phoneScreen = '/vendor_phoneScreen';
  static const home_vendorScreen = '/home_vendorScreen';
  static const vendor_profileScreen = '/vendor_profileScreen';
  static const faqScreen = '/faqScreen';
  static const favoriteScreen = '/favoriteScreen';
  static const certificateScreen = '/certificateScreen';
  static const licenceScreen = '/licenceScreen';
  static const categoryScreen = '/categoryScreen';
  static const changePasswordScreen = '/changePasswordScreen';
  static const privacyScreen = '/privacyScreen';
  static const termsScreen = '/termsScreen';
  static const documentScreen = '/documentScreen';
  static const reviewRatingScreen = '/review_ratingScreen';
  static const settingScreen = '/settingScreen';
  static const inboxScreen = '/inboxScreen';
  static const congratulationsScreen = '/congratulationsScreen';

  static const categoryPreviewScreen = '/categoryPreviewScreen';
  static const allCategoryScreen = '/all_categoryScreen';
  static const summaryScreen = '/summaryScreen';
  static const updateScreen = '/updateScreen';
  static const notificationScreen = '/notificationScreen';
  static const profileScreen = '/profileScreen';
  static const chatScreen = '/chatScreen';
  static const requestScreen = '/requestScreen';
  static const verifyScreen = '/verifyScreen';
  static const resetScreen = '/resetScreen';
  static const verificationScreen = '/verificationScreen';
  static const forgotScreen = '/forgotScreen';
  static const homeScreen = '/homeScreen';
  static const navigationScreen = '/navigationScreen';
  static const registerScreen = '/registerScreen';
  static const welcomeScreen = '/welcomeScreen';
  static const loginScreen = '/loginScreen';
  static const onboardScreen = '/onboardScreen';
  static const splashScreen = '/splashScreen';
}
